[pytest]
# 测试文件命名规则
python_files = test_*.py *_test.py

# 测试类命名规则
python_classes = Test*

# 测试函数命名规则
python_functions = test_*

# 自动添加命令行参数
addopts = -v --tb=short

# 测试搜索路径（可省略）
testpaths = testcases